name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.9.0

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Bump version (patch)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pnpm version patch --no-git-tag-version
          NEW_VER=$(node -pe "require('./package.json').version")
          git add package.json pnpm-lock.yaml
          git commit -m "chore(release): v${NEW_VER}"
          git tag "v${NEW_VER}"
          git push origin HEAD:main --follow-tags

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
